### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by jtagcat** [overnode-org/overnode#24]
'By default, a container will have an IP address assigned automatically out of the pool of available IP addresses: 10.40.0.1 - 10.47.255.254. Once a container is recreated, it may receive different IP address. A container does not change an IP address if it is restarted.' I know it's docker's fault as well, but ew.

**Comment by avkonst** [comment]
I think that would not be possible without the support from weavenet. And I believe they would not consider to add this feature because these are the IP addresses of the cluster's VPN maintained by weavenet. It has got enough big IP range for the largest deployments in the world :) Could you please elaborate more on the motivation for this feature?

**Comment by jtagcat** [comment]
I agree, I don't need this, the larger installations probably want something like k8s anyway.

Closing as wontfix until upstream does something.

Main reason being:

![caution legacy ip only; this product does not support the current generation of the internet protocol, ipv6](https://i.imgur.com/BoOxjZe.jpg)

**Comment by avkonst** [comment]
Waiting for the this ticket resolved: https://github.com/weaveworks/weave/issues/19
