### ISSUE TITLE
question

### ISSUE THREAD

**Issue by michabbb** [overnode-org/overnode#52]
hi, I read the docu and would like to ask: does this project cover replication of services and load balancing like swarm does? because I wasn't able to find anything about that topic. thanks.

**Comment by avkonst** [comment]
Hi, it does, but differently.

1. **For the replication**: you need to configure where a service should run: https://overnode.org/docs/managing-containers-workflow#launching-a-service

For example, the following service will be launched on all machines as per the following overnode.yaml config:

```yaml
id: echo-example
version: 3.7

echo:
    echo/service.yml: *
```
See placement rules for details: https://overnode.org/docs/overnode-yml-file-description#stacks

2. **For load balancing**: there are 2 cases in general. Load-balancing incoming traffic from clients and load-balancing and distribution of backend tasks. Overnode does not provide built-in feature for these, because there is no "one-fit-all" solution. However, you an achieve both using additional services. For example for load-balancing incoming traffic, you can use haproxy service on publicly listening hosts. For tasks distribution and load balancing, you can use a message queue, like kafka. 

Hope it helps. Let me know if there are more questions.

**Comment by michabbb** [comment]
thanks a lot, I didn't see that 😏
btw the link "placement rule" on this page 

https://overnode.org/docs/managing-containers-workflow

leads to a 404 

so under the hood, is there swarm used so I benefit from all the swarm features or does this project handle all the stuff on it's own? for example, I like swarm options to limit services based on the nodes memory for balancing, so that a node does not run too many instances of a single service.... is that possible with this project? 

thanks a lot!

**Comment by avkonst** [comment]
Thanks for reporting broken link. I will keep this ticket as a reminder to fix it.

The swarm is not used by the project. It uses weavenet instead and relies on static container placement, in contrast to dynamic in Swarm.

" so that a node does not run too many instances of a single service.... is that possible with this project?"
As the placement of containers is static, you control what services are launched, where and how many.

I also think that `overnode up` will fail, leaving some of the containers not launched, if the containers overall request to reserve more resources than available.

**Comment by michabbb** [comment]
okay, i guess i finally get the picture here 😏 thanks a lot for your help !
